[package]
name = "cairo_ml"
version = "0.1.0"
description = "Exploring Machine Learning in Cairo 1.0"
homepage = "https://github.com/raphaelDkhn/cairo_ml"

# Uncomment if you want to use dependencies
# Note: currently testing doesn't work with dependencies
# [dependencies]
# quaireaux = { git = "https://github.com/keep-starknet-strange/quaireaux.git" }